kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry-persistent-volume-claim
spec:
  storageClassName: docker-registry-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi